# Constants for SimonPi

# LED Pins
RED = 17
BLUE = 22
GREEN = 25
ORANGE = 24

# Geometric arrangement
LEDUP = BLUE
LEDLT = ORANGE
LEDRT = RED
LEDDN = GREEN

# Some cool designs
LEDALL = [LEDUP,LEDDN,LEDRT,LEDLT]
DNARROW = [LEDLT,LEDDN,LEDRT]
UPARROW = [LEDLT,LEDUP,LEDRT]
LTARROW = [LEDLT,LEDDN,LEDUP]
RTARROW = [LEDUP,LEDDN,LEDRT]

# Keypad bindings
SELECT = 9
START = 10
LPUP = 4
LPLT = 1
LPRT = 3
LPDN = 2
